routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// routes for guest middleware  and guard admin
Route::group(['prefix' => 'dashboard', 'middleware' => 'guest:admin'], function () {
    Route::get('/login', 'Auth\AuthController@login')->name('admin.login');
    Route::post('login', 'Auth\AuthController@doLogin')->name('admin.doLogin');
    Route::get('reloadCaptcha', 'Auth\AuthController@reloadCaptcha')->name('reloadCaptcha');
});

// routes for auth middleware  and guard admin

Route::group(
    ['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth:admin']], function () {

    Route::group(['prefix' => 'dashboard'], function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/logout', 'Auth\AuthController@logout')->name('admin.logout');
        Route::get('/praytime', 'DashboardController@prayTime')->name('admin.home');


        /*roles routes*/
        Route::get('/roles/data', 'RoleController@data')->name('roles.data');
        Route::post('roles/bulk-delete', 'RoleController@bulkDelete')->name('roles.bulkDelete');
        Route::resource('roles', 'RoleController')->except('show');
        /*end roles routes*/


        /* languages routes*/
        Route::get('/languages/data', 'LanguageController@data')->name('languages.data');
        Route::post('languages/bulk-delete', 'LanguageController@bulkDelete')->name('languages.bulkDelete');
        Route::post('languages/active', 'LanguageController@active')->name('languages.active');
        Route::resource('languages', 'LanguageController')->except('show');
        /* end languages routes */


        /* admins routes*/
        Route::get('/admins/data', 'AdminController@data')->name('admins.data');
        Route::post('admins/bulk-delete', 'AdminController@bulkDelete')->name('admins.bulkDelete');
        Route::resource('admins', 'AdminController')->except('show');
        /* end admins routes */

        /*quran readers*/
        Route::get('/quran-readers/data', 'QuranReaderController@data')->name('quran-readers.data');
        Route::post('quran-readers/bulk-delete', 'QuranReaderController@bulkDelete')->name('quran-readers.bulkDelete');
        Route::resource('quran-readers', 'QuranReaderController');
        /*end quran readers*/

        /*surah*/
        Route::get('surahs/data', 'SurahController@data')->name('surahs.data');
        Route::get('surahs/youtube-video', 'SurahController@getYoutubeVideo')->name('surahs.getVideo');
        Route::post('surahs/bulk-delete', 'SurahController@bulkDelete')->name('surahs.bulkDelete');
        Route::resource('surahs', 'SurahController');
        /*end surah*/

        /*hadith*/
        Route::get('hadiths/data', 'HadithController@data')->name('hadiths.data');
        Route::post('hadiths/bulk-delete', 'HadithController@bulkDelete')->name('hadiths.bulkDelete');
        Route::resource('hadiths', 'HadithController');
        /*end hadith*/

        /*prophet stories*/
        Route::get('prophet-stories/data', 'ProphetStoryController@data')->name('prophet-stories.data');
        Route::post('prophet-stories/bulk-delete', 'ProphetStoryController@bulkDelete')->name('prophet-stories.bulkDelete');
        Route::get('prophet-stories/delete/{id}', 'ProphetStoryController@delete')->name('prophet-stories.delete');
        Route::resource('prophet-stories', 'ProphetStoryController');
        /*prophet stories*/

        /*Hesn El muslim*/
        Route::get('hesn/data', 'HesnController@data')->name('hesn.data');
        Route::post('hesn/bulk-delete', 'HesnController@bulkDelete')->name('hesn.bulkDelete');
        Route::resource('hesn', 'HesnController');
        /*end  Hesn El muslim*/

        /* An Nawawy Forty*/
        Route::get('nawawy-forty/data', 'NawawyFortyController@data')->name('nawawy-forty.data');
        Route::post('nawawy-forty/bulk-delete', 'NawawyFortyController@bulkDelete')->name('nawawy-forty.bulkDelete');
        Route::get('nawawy-forty/delete/{id}', 'NawawyFortyController@delete')->name('nawawy-forty.delete');
        Route::resource('nawawy-forty', 'NawawyFortyController');
        /*An Nawawy Forty*/

        /* Video Kids*/
        Route::get('video-kids/data', 'VideoKidController@data')->name('video-kids.data');
        Route::post('video-kids/bulk-delete', 'VideoKidController@bulkDelete')->name('video-kids.bulkDelete');
        Route::resource('video-kids', 'VideoKidController');
        /*Video Kids*/


        /*libraries*/

        // library categories
        Route::get('library-categories/data', 'LibraryCategoryController@data')->name('library-categories.data');
        Route::post('library-categories/bulk-delete', 'LibraryCategoryController@bulkDelete')->name('library-categories.bulkDelete');
        Route::resource('library-categories', 'LibraryCategoryController');
        // end library categories

        // libraries
        Route::get('libraries/data', 'LibraryController@data')->name('libraries.data');
        Route::post('libraries/bulk-delete', 'LibraryController@bulkDelete')->name('libraries.bulkDelete');
        Route::get('/libraries/view-pdf/{id}', 'LibraryController@viewPdf')->name('libraries.viewPdf');
        Route::resource('libraries', 'LibraryController');
        // end libraries

        /*end libraries*/


        /* pray*/
        Route::get('prays/data', 'PrayController@data')->name('prays.data');
        Route::post('prays/bulk-delete', 'PrayController@bulkDelete')->name('prays.bulkDelete');
        Route::get('prays/delete/{id}', 'PrayController@delete')->name('prays.delete');
        Route::resource('prays', 'PrayController');
        /*end pray*/


        /* Orphan*/
        Route::get('orphans/data', 'OrphanController@data')->name('orphans.data');
        Route::post('orphans/bulk-delete', 'OrphanController@bulkDelete')->name('orphans.bulkDelete');
        Route::get('orphans/delete/{id}', 'OrphanController@delete')->name('orphans.delete');
        Route::get('orphans/get-city', 'OrphanController@getCountryCities')->name('getCountryCities');
        Route::post('orphans/approval', 'OrphanController@approval')->name('orphans.approval');
        Route::resource('orphans', 'OrphanController');
        /*end Orphan*/


        /* countries*/
        Route::get('countries/data', 'CountryController@data')->name('countries.data');
        Route::post('countries/bulk-delete', 'CountryController@bulkDelete')->name('countries.bulkDelete');
        Route::get('countries/delete/{id}', 'CountryController@delete')->name('countries.delete');
        Route::resource('countries', 'CountryController');
        /*end countries*/


        /* cities*/
        Route::get('cities/data', 'CityController@data')->name('cities.data');
        Route::post('cities/bulk-delete', 'CityController@bulkDelete')->name('cities.bulkDelete');
        Route::get('cities/delete/{id}', 'CityController@delete')->name('cities.delete');
        Route::resource('cities', 'CityController');
        /*end cities*/

        /* contact us*/
        Route::get('contact-us/data', 'ContactUsController@data')->name('contact-us.data');
        Route::post('contact-us/bulk-delete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
        Route::get('contact-us/delete/{id}', 'ContactUsController@delete')->name('contact-us.delete');
        Route::resource('contact-us', 'ContactUsController');
        /*end contact us*/


        /* contact us*/
        Route::get('dead/data', 'DeadController@data')->name('dead.data');
        Route::post('dead/bulk-delete', 'DeadController@bulkDelete')->name('dead.bulkDelete');
        Route::get('dead/delete/{id}', 'DeadController@delete')->name('dead.delete');
        Route::post('dead/approval', 'DeadController@approval')->name('dead.approval');
        Route::resource('dead', 'DeadController');
        /*end contact us*/

        /*settings*/
        Route::resource('settings', 'SettingController');
        /*end settings*/
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create asidsomething great!
|
*/


Route::get('/', 'FrontController@index');
//Route::view('/website', 'website.index2');
//  Quran //
Route::get('/quran', 'QuranController@index')->name('website.quran.index');
Route::get('/quran/read', 'QuranController@read');
Route::get('/quran/listen/{reader_id?}/', 'QuranController@listen')->name('readerSearch');
Route::get('quran/get-surah', 'QuranController@getSurah')->name('quran.getSurah');
Route::get('quran/get-video', 'QuranController@getVideos')->name('quran.getVideos');
Route::get('/quran/videos', 'QuranController@videos')->name('quran.videos');
Route::get('/quran-videos/{id}', 'QuranController@show');
// end Quran

// hadith
Route::get('/hadith', 'HadithController@index');
Route::get('/hadith/listen', 'HadithController@listen')->name('hadith.listen');
Route::get('/hadith/videos', 'HadithController@videos')->name('hadith.videos');
Route::get('/hadith/getAudio', 'HadithController@getAudio')->name('hadith.getAudio');
Route::get('/hadith-videos/{id}', 'HadithController@show');
//end hadith

// prophet's stories
Route::get('/prophets-stories', 'ProphetController@index');
Route::get('/prophets-stories/read', 'ProphetController@read')->name('prophet.read');
Route::get('/prophets-stories/listen', 'ProphetController@listen')->name('prophet.listen');
Route::get('/prophets-stories/videos', 'ProphetController@videos')->name('prophet.videos');
Route::get('/prophets-stories-videos/{id}', 'ProphetController@show');
// end prophet's story

// Hesn el-muslim
Route::get('/hesn-elmuslim', 'HesnController@index');
Route::get('/hesn-elmuslim/listen', 'HesnController@listen');
Route::get('/hesn-elmuslim/videos', 'HesnController@videos');
Route::get('/hesn-elmuslim-videos/{id}', 'HesnController@show');
// end Hesn el-muslim


// Arbaon Nwawia
Route::get('arboon-nwawia', 'NwawiaController@index');
Route::get('/arboon-nwawia/read', 'NwawiaController@read');
Route::get('/arboon-nwawia/listen', 'NwawiaController@listen');
Route::get('/arboon-nwawia/videos', 'NwawiaController@videos');
Route::get('/arboon-nwawia-videos/{id}', 'NwawiaController@show');

// end Arbaon Nwawia

// kids videos
Route::get('/kid-videos', 'KidvideoController@index');
Route::get('/kid-videos/{id}', 'KidvideoController@show');
// end kids videos

// masbaha
Route::get('/masbaha', 'MasbahaController@index');
// end masbaha

// libraries
Route::get('/libraries', 'LibraryController@index');
Route::get('/libraries/{id}', 'LibraryController@showCategory')->name('libraries.showCategory');
Route::get('/libraries/book/{id}', 'LibraryController@readBook')->name('libraries.readBook');
Route::get('/book-search/', 'LibraryController@bookSearch')->name('libraries.books_search');
//end libraries

// pray for death
Route::get('/pray', 'PrayController@index');
Route::get('pray/read', 'PrayController@read');
Route::get('pray/listen', 'PrayController@listen');
Route::get('pray/videos', 'PrayController@videos');
Route::get('/pray-videos/{id}', 'PrayController@show');

// end pray for death

// add orphan
Route::get('/add-orphan', 'OrphanController@create');
Route::post('add-orphan', 'OrphanController@store')->name('website.storeOrphan');
//  add orphan

//settings
Route::get('/settings', 'SettingsController@edit');
Route::post('/settings/', 'SettingsController@store');

//end settings

// add dead
Route::get('/add-dead', 'DeadController@create');
Route::post('/add-dead', 'DeadController@store');
Route::get('/D/{id}', 'DeadController@show')->name('dead.show');
// end add dead

// share app

Route::view('share', 'website.pages.share');


// get city
Route::get('/get-city', 'FrontController@getCity')->name('website.getCity');
Route::get('/get-dead', 'FrontController@getDeads')->name('website.getDeads');
//end city

// get pray times
Route::get('getTimeZone', 'FrontController@getPrayTimes')->name('website.getPrayTimes');

// end pray times
//Route::get('/fire_event', function () {
//
//    event(new \App\Events\PrayNotification('welcome'));
//})->name('fire_event');

Route::view('/contact-us', 'website.pages.contact');
Route::post('contact-us', 'FrontController@contact')->name('website.contact');

Route::view('/about-us', 'website.pages.about');

Route::view('test-player', 'website.test_player');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Hesn.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Translatable;

use Illuminate\Database\Eloquent\Model;

class Hesn extends Model
{
    use Translatable;
    protected $table = 'hesns';
    protected $guarded = [];
    public $translatedAttributes = ['title','meta_title','meta_description','meta_keywords'];
}

app/Http/Controllers/Dashboard/Api/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard\Api;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Traits\upload;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    use upload;

    public function __construct()
    {
        $this->middleware(['auth:admin-api', 'permission:read_admins'])->only('index');
        $this->middleware(['auth:admin-api', 'permission:create_admins'])->only('create');
        $this->middleware(['auth:admin-api', 'permission:update_admins'])->only('edit');
        $this->middleware(['auth:admin-api', 'permission:delete_admins'])->only('delete');
    }


    public function store(Request $request)
    {
        $data = $request->except('_token', 'password', 'role', 'password_confirmation');


        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:admins,email',
            'password' => 'required|confirmed',
            'role' => 'integer|required',
        ]);
        if ($request->has('password')) {
            $data['password'] = bcrypt($request->password);
        }//end if statement
        if ($request->hasFile('photo')) {
            $name = $this->upload($request->photo, 'admins');
            $data['photo'] = $name;

        }//end if statement

        $admin = Admin::create($data);
        $admin->attachRole($request->role);
        return redirect()->route('admins.index')->with('success', 'data stored successfully');


    }


    public function update(Request $request, $id)
    {
        $admin = Admin::findOrFail($id);
        $data = $request->except(['_token', '_method', 'role']);


        if ($request->password != null) {
            $data['password'] = bcrypt($request->password);
        } else {
            $data['password'] = $admin->password;
        }
        if ($request->hasFile('photo')) {

            $this->deleteoldPhoto($admin->photo, 'admins');
            $name = $this->upload($request->photo, 'admins');
            $data['photo'] = $name;

        }//end if statement

        $admin->update($data);

        $admin->syncRoles([$request->role]);

        return redirect()->route('admins.index')->with('success', 'data updated successfully');
    }


    public function destroy($id)
    {
        $admin = Admin::findOrFail($id);
        $this->deleteoldPhoto($admin->photo, 'admins');
        $admin->delete();
        return redirect()->route('admins.index')->with('success', 'data deleted successfully');
    }

    public function bulkDelete(Request $request)
    {

        foreach ($request->items as $item) {
            $admin = Admin::find($item);
            $this->deleteoldPhoto($admin->photo, 'admins');
        }
        Admin::destroy($request->items);

        return redirect()->route('admins.index')->with('success', 'data deleted successfully');


    }//end of bulkDelete function
}

app/Http/Controllers/Dashboard/Api/HadithController.php
<?php

namespace App\Http\Controllers\Dashboard\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\HadithRequest;
use App\Models\Hadith;
use App\Services\HadithService;

class HadithController extends Controller
{


    public $service;

    public function __construct(HadithService $service)
    {

        $this->service = $service;

    }//end of __construct function


    public function store(HadithRequest $request)
    {
        $data = $this->service->handleUploads($request);
        Hadith::create($data);
        return redirect()->route('hadiths.index')->with('success', 'data stored successfully');
    }


    public function update(HadithRequest $request, $id)
    {
        $data = $this->service->handleUploads($request, $id);
        $hadith = Hadith::find($id);
        $hadith->update($data);

        return redirect()->route('hadiths.index')->with('success', 'data updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hadith = Hadith::find($id);
        $this->service->deleteFiles($hadith);
        $hadith->delete();
        return redirect()->back()->with('success', 'data deleted successfully');
    }

    public function bulkDelete()
    {
        $this->service->deleteItems(request()->items);
        Hadith::destroy(request()->items);

        return redirect()->back()->with('success', 'data deleted successfully');

    }//end of bulkDelete function
}

app/Http/Controllers/Dashboard/Api/ProphetStoryController.php
<?php

namespace App\Http\Controllers\Dashboard\Api;

use App\Http\Controllers\Controller;

class ProphetStoryController extends Controller
{
    //
}

resources/views/dashboard/hesn/actions.blade.php
<div class="d-flex align-items-center list-action">

    <a class="btn btn-success" href="{{route('hesn.edit',encrypt($raw->id))}}"><i class="ri-pencil-line mr-0"></i> تعديل</a>


    <form method="post" action="{{route('hesn.destroy',$raw->id)}}">
        @csrf
        @method('delete')
        <button class="btn btn-danger delete_btn " type="submit">حذف</button>

    </form>


</div>


<script>
    $('.delete_btn').on('click', function (e) {
        e.preventDefault();

        Swal.fire({
            title: 'هل أنت  متأكد',
            text: "يمكنك التراجع عن هذا الأمر!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'نعم, حذف!',
            cancelButtonText: 'ألغاء'
        }).then((result) => {
            if (result.isConfirmed) {
                $(this).parent('form').submit();
            }
        })

    })
</script>

resources/views/dashboard/hesn/create.blade.php
@extends('dashboard.layouts.master')

@push('style')
@endpush
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <form action="{{route('hesn.store')}}" method="post" enctype="multipart/form-data">
                @csrf

                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">@lang('site.add_story')</h4>
                        </div>
                        <a href="{{route('hesn.index')}}" class="btn btn-outline-secondary add-list">
                            رجوع
                            <i class="las la-long-arrow-alt-left"></i></a>
                    </div>
                    <div class="card-body">
                        <ul class="nav nav-tabs" id="myTab-1" role="tablist">
                            @foreach(activeLanguages() as $lang)
                                <li class="nav-item">
                                    <a class="nav-link {{$loop->first ? 'active':''}}" id="one-tab" data-toggle="tab"
                                       href="#{{$lang->locale}}" role="tab" aria-controls="one"
                                       aria-selected="true">{{$lang->name}}</a>
                                </li>
                            @endforeach


                        </ul>
                        <div class="tab-content checkout-form checkout-form-custom" id="myTabContent-2">
                            @foreach(activeLanguages() as $lang)
                                <div class="tab-pane fade {{$loop->first ? 'active':''}} show" id="{{$lang->locale}}"
                                     role="tabpanel" aria-labelledby="one-tab">
                                    <div class="flex-divs mb-3">
                                        <div class="input-block">
                                            <label>@lang('site.name') ( {{$lang->name}} )</label>
                                            <input type="text" name="{{$lang->locale}}[title]">

                                            @error($lang->locale.'.title')
                                            <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    @include('dashboard.includes.seo_inputs',['lang'=>$lang])
                                </div>

                            @endforeach

                            <div class="btm-part">
                                <h4 class="title mb-3">الفيديو</h4>
                                <div class="flex-radio">
                                    <label for="youtube">
                                        <input checked type="radio" class="" id="youtube" value="url" name="video_type">
                                        <strong>رابط يوتيوب</strong>
                                    </label>
                                    <label for="file">
                                        <input type="radio" id="file" value="file" name="video_type">
                                        <strong>ملف</strong>
                                    </label>
                                </div>
                                <div class="flex-divs">
                                    <div class="input-block">
                                        <input type="url" name="video" class="video_url" placeholder="الصق الرابط هنا">
                                        <input type="file" name="video" class="video_file" hidden>
                                    </div>
                                </div>
                                <div class="mt-2 flex-divs">
                                    <iframe hidden id="video_frame" width="" height="300" src="">
                                    </iframe>
                                </div>
                            </div>

                            <div class="btm-part">
                                <h4 class="title mb-3">ملف الصوت</h4>
                                <div class="flex-divs">
                                    <div class="input-block">
                                        <input type="file" name="audio">
                                    </div>
                                </div>
                                <div class="mt-2 flex-divs" id="audio">
                                    <audio controls class="audio-custom">
                                        <source src="" type="audio/ogg">
                                    </audio>
                                </div>
                            </div>

                            <div class="btm-part">
                                <h4 class="title mb-3">الصوره</h4>
                                <div class="flex-divs">
                                    <div class="input-block">
                                        <input type="file" name="photo">
                                    </div>
                                </div>


                            </div>

                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> حفظ</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('javascript')


@endpush

resources/views/dashboard/hesn/edit.blade.php
@extends('dashboard.layouts.master')

@push('style')
@endpush
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <form action="{{route('hesn.update',$hesn->id)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')

                <input type="hidden" value="{{$hesn->id}}" name="id">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">تعديل</h4>
                        </div>
                        <a href="{{route('hesn.index')}}" class="btn btn-outline-secondary add-list">
                            رجوع
                            <i class="las la-long-arrow-alt-left"></i></a>
                    </div>
                    <div class="card-body">
                        <ul class="nav nav-tabs" id="myTab-1" role="tablist">
                            @foreach(activeLanguages() as $lang)
                                <li class="nav-item">
                                    <a class="nav-link {{$loop->first ? 'active':''}}" id="one-tab" data-toggle="tab"
                                       href="#{{$lang->locale}}" role="tab" aria-controls="one"
                                       aria-selected="true">{{$lang->name}}</a>
                                </li>
                            @endforeach


                        </ul>
                        <div class="tab-content checkout-form checkout-form-custom" id="myTabContent-2">
                            @foreach(activeLanguages() as $lang)
                                <div class="tab-pane fade {{$loop->first ? 'active':''}} show" id="{{$lang->locale}}"
                                     role="tabpanel" aria-labelledby="one-tab">
                                    <div class="flex-divs mb-3">
                                        <div class="input-block">
                                            <label>@lang('site.name') ( {{$lang->name}} )</label>
                                            <input value="{{$hesn->translate($lang->locale)['title']}}" type="text"
                                                   name="{{$lang->locale}}[title]">

                                            @error($lang->locale.'.name')
                                            <span class="text-danger">{{$message}}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    @include('dashboard.includes.seo_inputs',['lang'=>$lang,'model'=>$hesn])
                                </div>

                            @endforeach

                            <div class="btm-part">
                                <h4 class="title mb-3">الفيديو</h4>
                                <div class="flex-radio">
                                    <label for="youtube">
                                        <input {{$hesn->video_type == 'url' ? 'checked':''}} type="radio" class=""
                                               id="youtube" value="url" name="video_type">
                                        <strong>رابط يوتيوب</strong>
                                    </label>
                                    <label for="file">
                                        <input {{$hesn->video_type == 'file' ? 'checked':''}} type="radio" id="file"
                                               value="file" name="video_type">
                                        <strong>ملف</strong>
                                    </label>
                                </div>
                                <div class="flex-divs">
                                    <div class="input-block">
                                        <input {{$hesn->video_type == 'url' ? '':'hidden'}}
                                               value="{{$hesn->video_type == 'url' ? $hesn->video:''}}" type="url" name="video"
                                               class="video_url" placeholder="الصق الرابط هنا">
                                        <input type="file" name="video" class="video_file"
                                            {{$hesn->video_type == 'file' ? '':'hidden'}}>
                                    </div>
                                </div>
                                <div class="mt-2 flex-divs">
                                    <iframe id="video_frame" height="300"
                                            src="{{$hesn->video_type == 'file' ? asset('uploads/hesn/videos/'.$hesn->video):getYoutubeId($hesn->video)}}">
                                    </iframe>
                                </div>
                            </div>

                            <div class="btm-part">
                                <h4 class="title mb-3">ملف الصوت</h4>
                                <div class="flex-divs">
                                    <div class="input-block">
                                        <input type="file" name="audio">
                                    </div>
                                </div>
                                <div class="mt-2 flex-divs" id="audio">
                                    <audio controls class="audio-custom">
                                        <source src="{{asset('uploads/hesn/audios/'.$hesn->audio)}}" type="audio/ogg">
                                    </audio>
                                </div>
                            </div>

                            <div class="btm-part">
                                <h4 class="title mb-3">الصوره</h4>
                                <div class="flex-divs">
                                    <div class="input-block">
                                        <input type="file" name="photo">
                                    </div>
                                </div>

                                @if($hesn->photo)
                                    <img width="100" height="100" src="{{asset('images/hesns/'.$hesn->photo)}}" alt="">
                                @endif

                            </div>

                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> حفظ</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('javascript')

@endpush