routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// routes for guest middleware  and guard admin
Route::group(['prefix' => 'dashboard', 'middleware' => 'guest:admin'], function () {
    Route::get('/login', 'Auth\AuthController@login')->name('admin.login');
    Route::post('login', 'Auth\AuthController@doLogin')->name('admin.doLogin');
    Route::get('reloadCaptcha', 'Auth\AuthController@reloadCaptcha')->name('reloadCaptcha');
});

// routes for auth middleware  and guard admin

Route::group(
    ['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'auth:admin']], function () {

    Route::group(['prefix' => 'dashboard'], function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/logout', 'Auth\AuthController@logout')->name('admin.logout');
        Route::get('/praytime', 'DashboardController@prayTime')->name('admin.home');


        /*roles routes*/
        Route::get('/roles/data', 'RoleController@data')->name('roles.data');
        Route::post('roles/bulk-delete', 'RoleController@bulkDelete')->name('roles.bulkDelete');
        Route::resource('roles', 'RoleController')->except('show');
        /*end roles routes*/


        /* languages routes*/
        Route::get('/languages/data', 'LanguageController@data')->name('languages.data');
        Route::post('languages/bulk-delete', 'LanguageController@bulkDelete')->name('languages.bulkDelete');
        Route::post('languages/active', 'LanguageController@active')->name('languages.active');
        Route::resource('languages', 'LanguageController')->except('show');
        /* end languages routes */


        /* admins routes*/
        Route::get('/admins/data', 'AdminController@data')->name('admins.data');
        Route::post('admins/bulk-delete', 'AdminController@bulkDelete')->name('admins.bulkDelete');
        Route::resource('admins', 'AdminController')->except('show');
        /* end admins routes */

        /*quran readers*/
        Route::get('/quran-readers/data', 'QuranReaderController@data')->name('quran-readers.data');
        Route::post('quran-readers/bulk-delete', 'QuranReaderController@bulkDelete')->name('quran-readers.bulkDelete');
        Route::resource('quran-readers', 'QuranReaderController');
        /*end quran readers*/

        /*surah*/
        Route::get('surahs/data', 'SurahController@data')->name('surahs.data');
        Route::get('surahs/youtube-video', 'SurahController@getYoutubeVideo')->name('surahs.getVideo');
        Route::post('surahs/bulk-delete', 'SurahController@bulkDelete')->name('surahs.bulkDelete');
        Route::resource('surahs', 'SurahController');
        /*end surah*/

        /*hadith*/
        Route::get('hadiths/data', 'HadithController@data')->name('hadiths.data');
        Route::post('hadiths/bulk-delete', 'HadithController@bulkDelete')->name('hadiths.bulkDelete');
        Route::resource('hadiths', 'HadithController');
        /*end hadith*/

        /*prophet stories*/
        Route::get('prophet-stories/data', 'ProphetStoryController@data')->name('prophet-stories.data');
        Route::post('prophet-stories/bulk-delete', 'ProphetStoryController@bulkDelete')->name('prophet-stories.bulkDelete');
        Route::get('prophet-stories/delete/{id}', 'ProphetStoryController@delete')->name('prophet-stories.delete');
        Route::resource('prophet-stories', 'ProphetStoryController');
        /*prophet stories*/

        /*Hesn El muslim*/
        Route::get('hesn/data', 'HesnController@data')->name('hesn.data');
        Route::post('hesn/bulk-delete', 'HesnController@bulkDelete')->name('hesn.bulkDelete');
        Route::resource('hesn', 'HesnController');
        /*end  Hesn El muslim*/

        /* An Nawawy Forty*/
        Route::get('nawawy-forty/data', 'NawawyFortyController@data')->name('nawawy-forty.data');
        Route::post('nawawy-forty/bulk-delete', 'NawawyFortyController@bulkDelete')->name('nawawy-forty.bulkDelete');
        Route::get('nawawy-forty/delete/{id}', 'NawawyFortyController@delete')->name('nawawy-forty.delete');
        Route::resource('nawawy-forty', 'NawawyFortyController');
        /*An Nawawy Forty*/

        /* Video Kids*/
        Route::get('video-kids/data', 'VideoKidController@data')->name('video-kids.data');
        Route::post('video-kids/bulk-delete', 'VideoKidController@bulkDelete')->name('video-kids.bulkDelete');
        Route::resource('video-kids', 'VideoKidController');
        /*Video Kids*/


        /*libraries*/

        // library categories
        Route::get('library-categories/data', 'LibraryCategoryController@data')->name('library-categories.data');
        Route::post('library-categories/bulk-delete', 'LibraryCategoryController@bulkDelete')->name('library-categories.bulkDelete');
        Route::resource('library-categories', 'LibraryCategoryController');
        // end library categories

        // libraries
        Route::get('libraries/data', 'LibraryController@data')->name('libraries.data');
        Route::post('libraries/bulk-delete', 'LibraryController@bulkDelete')->name('libraries.bulkDelete');
        Route::get('/libraries/view-pdf/{id}', 'LibraryController@viewPdf')->name('libraries.viewPdf');
        Route::resource('libraries', 'LibraryController');
        // end libraries

        /*end libraries*/


        /* pray*/
        Route::get('prays/data', 'PrayController@data')->name('prays.data');
        Route::post('prays/bulk-delete', 'PrayController@bulkDelete')->name('prays.bulkDelete');
        Route::get('prays/delete/{id}', 'PrayController@delete')->name('prays.delete');
        Route::resource('prays', 'PrayController');
        /*end pray*/


        /* Orphan*/
        Route::get('orphans/data', 'OrphanController@data')->name('orphans.data');
        Route::post('orphans/bulk-delete', 'OrphanController@bulkDelete')->name('orphans.bulkDelete');
        Route::get('orphans/delete/{id}', 'OrphanController@delete')->name('orphans.delete');
        Route::get('orphans/get-city', 'OrphanController@getCountryCities')->name('getCountryCities');
        Route::post('orphans/approval', 'OrphanController@approval')->name('orphans.approval');
        Route::resource('orphans', 'OrphanController');
        /*end Orphan*/


        /* countries*/
        Route::get('countries/data', 'CountryController@data')->name('countries.data');
        Route::post('countries/bulk-delete', 'CountryController@bulkDelete')->name('countries.bulkDelete');
        Route::get('countries/delete/{id}', 'CountryController@delete')->name('countries.delete');
        Route::resource('countries', 'CountryController');
        /*end countries*/


        /* cities*/
        Route::get('cities/data', 'CityController@data')->name('cities.data');
        Route::post('cities/bulk-delete', 'CityController@bulkDelete')->name('cities.bulkDelete');
        Route::get('cities/delete/{id}', 'CityController@delete')->name('cities.delete');
        Route::resource('cities', 'CityController');
        /*end cities*/

        /* contact us*/
        Route::get('contact-us/data', 'ContactUsController@data')->name('contact-us.data');
        Route::post('contact-us/bulk-delete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
        Route::get('contact-us/delete/{id}', 'ContactUsController@delete')->name('contact-us.delete');
        Route::resource('contact-us', 'ContactUsController');
        /*end contact us*/


        /* contact us*/
        Route::get('dead/data', 'DeadController@data')->name('dead.data');
        Route::post('dead/bulk-delete', 'DeadController@bulkDelete')->name('dead.bulkDelete');
        Route::get('dead/delete/{id}', 'DeadController@delete')->name('dead.delete');
        Route::post('dead/approval', 'DeadController@approval')->name('dead.approval');
        Route::resource('dead', 'DeadController');
        /*end contact us*/

        /*settings*/
        Route::resource('settings', 'SettingController');
        /*end settings*/
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create asidsomething great!
|
*/


Route::get('/', 'FrontController@index');
//Route::view('/website', 'website.index2');
//  Quran //
Route::get('/quran', 'QuranController@index')->name('website.quran.index');
Route::get('/quran/read', 'QuranController@read');
Route::get('/quran/listen/{reader_id?}/', 'QuranController@listen')->name('readerSearch');
Route::get('quran/get-surah', 'QuranController@getSurah')->name('quran.getSurah');
Route::get('quran/get-video', 'QuranController@getVideos')->name('quran.getVideos');
Route::get('/quran/videos', 'QuranController@videos')->name('quran.videos');
Route::get('/quran-videos/{id}', 'QuranController@show');
// end Quran

// hadith
Route::get('/hadith', 'HadithController@index');
Route::get('/hadith/listen', 'HadithController@listen')->name('hadith.listen');
Route::get('/hadith/videos', 'HadithController@videos')->name('hadith.videos');
Route::get('/hadith/getAudio', 'HadithController@getAudio')->name('hadith.getAudio');
Route::get('/hadith-videos/{id}', 'HadithController@show');
//end hadith

// prophet's stories
Route::get('/prophets-stories', 'ProphetController@index');
Route::get('/prophets-stories/read', 'ProphetController@read')->name('prophet.read');
Route::get('/prophets-stories/listen', 'ProphetController@listen')->name('prophet.listen');
Route::get('/prophets-stories/videos', 'ProphetController@videos')->name('prophet.videos');
Route::get('/prophets-stories-videos/{id}', 'ProphetController@show');
// end prophet's story

// Hesn el-muslim
Route::get('/hesn-elmuslim', 'HesnController@index');
Route::get('/hesn-elmuslim/listen', 'HesnController@listen');
Route::get('/hesn-elmuslim/videos', 'HesnController@videos');
Route::get('/hesn-elmuslim-videos/{id}', 'HesnController@show');
// end Hesn el-muslim


// Arbaon Nwawia
Route::get('arboon-nwawia', 'NwawiaController@index');
Route::get('/arboon-nwawia/read', 'NwawiaController@read');
Route::get('/arboon-nwawia/listen', 'NwawiaController@listen');
Route::get('/arboon-nwawia/videos', 'NwawiaController@videos');
Route::get('/arboon-nwawia-videos/{id}', 'NwawiaController@show');

// end Arbaon Nwawia

// kids videos
Route::get('/kid-videos', 'KidvideoController@index');
Route::get('/kid-videos/{id}', 'KidvideoController@show');
// end kids videos

// masbaha
Route::get('/masbaha', 'MasbahaController@index');
// end masbaha

// libraries
Route::get('/libraries', 'LibraryController@index');
Route::get('/libraries/{id}', 'LibraryController@showCategory')->name('libraries.showCategory');
Route::get('/libraries/book/{id}', 'LibraryController@readBook')->name('libraries.readBook');
Route::get('/book-search/', 'LibraryController@bookSearch')->name('libraries.books_search');
//end libraries

// pray for death
Route::get('/pray', 'PrayController@index');
Route::get('pray/read', 'PrayController@read');
Route::get('pray/listen', 'PrayController@listen');
Route::get('pray/videos', 'PrayController@videos');
Route::get('/pray-videos/{id}', 'PrayController@show');

// end pray for death

// add orphan
Route::get('/add-orphan', 'OrphanController@create');
Route::post('add-orphan', 'OrphanController@store')->name('website.storeOrphan');
//  add orphan

//settings
Route::get('/settings', 'SettingsController@edit');
Route::post('/settings/', 'SettingsController@store');

//end settings

// add dead
Route::get('/add-dead', 'DeadController@create');
Route::post('/add-dead', 'DeadController@store');
Route::get('/D/{id}', 'DeadController@show')->name('dead.show');
// end add dead

// share app

Route::view('share', 'website.pages.share');


// get city
Route::get('/get-city', 'FrontController@getCity')->name('website.getCity');
Route::get('/get-dead', 'FrontController@getDeads')->name('website.getDeads');
//end city

// get pray times
Route::get('getTimeZone', 'FrontController@getPrayTimes')->name('website.getPrayTimes');

// end pray times
//Route::get('/fire_event', function () {
//
//    event(new \App\Events\PrayNotification('welcome'));
//})->name('fire_event');

Route::view('/contact-us', 'website.pages.contact');
Route::post('contact-us', 'FrontController@contact')->name('website.contact');

Route::view('/about-us', 'website.pages.about');

Route::view('test-player', 'website.test_player');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Dashboard/LibraryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\LibraryRequest;
use App\Models\Library;
use App\Models\LibraryCategory;
use App\Services\LibraryService;
use Illuminate\Contracts\Encryption\DecryptException;
use Yajra\DataTables\Facades\DataTables;

class LibraryController extends Controller
{

    public $service;

    public function __construct(LibraryService $service)
    {
        $this->service = $service;
    }

    public function index()
    {

        return view('dashboard.libraries.libraries.index');

    }//end of index function

    public function data()
    {
        $library = Library::with('translations')->OrderBy('id', 'desc')->get();

        return DataTables::of($library)
            ->addColumn('actions', function ($raw) {

                return view('dashboard.libraries.libraries.actions', compact('raw'));
            })
            ->addColumn('check_all', function ($raw) {
                return '<input type="checkbox" class="checkedBtn" name="items[]" value="' . $raw->id . '">';
            })
            ->rawColumns(['check_all' => 'check_all'])
            ->make(true);


    }//end of data function

    public function create()
    {
        $categories = LibraryCategory::with('translations')->get();
        return view('dashboard.libraries.libraries.create', compact('categories'));


    }//end of create function

    public function store(LibraryRequest $request)
    {

        $data = $this->service->handleUploads($request);
        Library::create($data);

        return redirect()->route('libraries.index')->with('success', 'data stored successfully');

    }//end of store function

    public function edit($id)
    {
        try {
            $library = Library::find(decrypt($id));
        }catch (DecryptException $exception){
            abort(404);
        }
        $categories = LibraryCategory::with('translations')->get();
        return view('dashboard.libraries.libraries.edit', compact('library', 'categories'));


    }//end of edit function

    public function update(LibraryRequest $request, $id)
    {
        $library = Library::find($id);
        $data = $this->service->handleUploads($request, $id);
        $library->update($data);
        return redirect()->route('libraries.index')->with('success', 'data updated successfully');

    }//end of update function

    public function destroy($id)
    {
        $library = Library::find($id);
        $this->service->deleteFiles($library);
        $library->delete();
        return redirect()->route('libraries.index')->with('success', 'data deleted successfully');

    }//end of destroy function

    public function bulkDelete()
    {
        $this->service->deleteItems(request()->items);
        Library::destroy(request()->items);
        return redirect()->route('libraries.index')->with('success', 'data deleted successfully');

    }//end of bulkDelete function

    public function viewPdf($id)
    {
        $library = Library::find($id);
        return view('dashboard.libraries.libraries.view_pdf', compact('library'));
    }//end of viewPdf function
}

app/Http/Controllers/LibraryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Library;
use App\Models\LibraryCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class LibraryController extends Controller
{
    public function index()
    {
        $categories = LibraryCategory::query()->get();
        return view('website.libraries.index', compact('categories'));

    }//end of index function

    public function showCategory($id)
    {

        $books = LibraryCategory::with('translations', 'books')->findOrFail($id)->books;


        return view('website.libraries.books', compact('books'));


    }//end of showCategory function

    public function readBook($id)
    {
        $book = Library::findOrFail($id);

        return view('website.libraries.read', compact('book'));


    }//end of readBook function

    public function bookSearch(Request $request)
    {
        $book_name = $request->book_name;
        $cat_id = $request->cat_id;
        $books = Library::with('translations')->when($request->book_name, function ($q) use ($book_name, $cat_id) {
            if (isset($book_name) && $book_name != '') {
                $q->whereTranslationLike('name', '%' . $book_name . '%');

            }

        })->whereCategoryId($cat_id)->get();
        $view = View::make('website.libraries.search', compact('books'))->render();

        return response()->json(['view' => $view], 200);

    }//end of bookSearch function
}

resources/views/dashboard/libraries/categories/actions.blade.php
<div class="d-flex align-items-center list-action">

    <a class="btn btn-success" href="{{route('library-categories.edit',encrypt($raw->id))}}"><i class="ri-pencil-line mr-0"></i> تعديل</a>


    <form id="form" method="post" action="{{route('library-categories.destroy',$raw->id)}}">
        @csrf
        @method('delete')
        <button class="btn btn-danger delete_btn " type="submit">حذف</button>

    </form>


</div>


<script>
    $('.delete_btn').on('click', function (e) {
        e.preventDefault();

        Swal.fire({
            title: 'هل أنت  متأكد',
            text: "يمكنك التراجع عن هذا الأمر!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'نعم, حذف!',
            cancelButtonText: 'ألغاء'
        }).then((result) => {
            if (result.isConfirmed) {
                $(this).parent('form').submit();
            }
        })

    })
</script>

resources/views/dashboard/libraries/categories/create.blade.php
@extends('dashboard.layouts.master')

@push('style')
@endpush
@section('content')
<div class="row">
    <div class="col-sm-12">
        <form action="{{route('library-categories.store')}}" method="post" enctype="multipart/form-data">
            @csrf

            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">إضافه قسم</h4>
                    </div>
                    <a href="{{route('library-categories.index')}}" class="btn btn-outline-secondary add-list">
                        رجوع
                        <i class="las la-long-arrow-alt-left"></i></a>
                </div>
                <div class="card-body">
                    <ul class="nav nav-tabs" id="myTab-1" role="tablist">
                        @foreach(activeLanguages() as $lang)
                        <li class="nav-item">
                            <a class="nav-link {{$loop->first ? 'active':''}}" id="one-tab" data-toggle="tab"
                                href="#{{$lang->locale}}" role="tab" aria-controls="one"
                                aria-selected="true">{{$lang->name}}</a>
                        </li>
                        @endforeach


                    </ul>
                    <div class="tab-content checkout-form checkout-form-custom" id="myTabContent-2">
                        @foreach(activeLanguages() as $lang)
                        <div class="tab-pane fade {{$loop->first ? 'active':''}} show" id="{{$lang->locale}}"
                            role="tabpanel" aria-labelledby="one-tab">
                            <div class="flex-divs mb-3">
                                <div class="input-block">
                                    <label>@lang('site.name') ( {{$lang->name}} )</label>
                                    <input type="text" name="{{$lang->locale}}[name]">

                                    @error($lang->locale.'.name')
                                    <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                            </div>

                            @include('dashboard.includes.seo_inputs',['lang'=>$lang])
                        </div>

                        @endforeach
                        <div class="btm-part">
                            <h4 class="title mb-3">الصورة</h4>
                            <div class="flex-divs">
                                <div class="input-block">
                                    <input type="file" id="image" class="" name="photo" />
                                </div>
                            </div>
                            <div class="mt-2 flex-divs">
                            <img class="image_preview" src="{{asset('default.png')}}" alt="">
                            </div>
                        </div>

                    </div>

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> حفظ</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('javascript')
{{--    --}}
@endpush

resources/views/dashboard/libraries/categories/edit.blade.php
@extends('dashboard.layouts.master')

@push('style')
@endpush
@section('content')
<div class="row">
    <div class="col-sm-12">
        <form action="{{route('library-categories.update',$category->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')

            <input type="hidden" value="{{$category->id}}" name="id">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">تعديل قسم</h4>
                    </div>
                    <a href="{{route('library-categories.index')}}" class="btn btn-outline-secondary add-list">
                        رجوع
                        <i class="las la-long-arrow-alt-left"></i></a>
                </div>
                <div class="card-body">
                    <ul class="nav nav-tabs" id="myTab-1" role="tablist">
                        @foreach(activeLanguages() as $lang)
                        <li class="nav-item">
                            <a class="nav-link {{$loop->first ? 'active':''}}" id="one-tab" data-toggle="tab"
                                href="#{{$lang->locale}}" role="tab" aria-controls="one"
                                aria-selected="true">{{$lang->name}}</a>
                        </li>
                        @endforeach


                    </ul>
                    <div class="tab-content checkout-form checkout-form-custom" id="myTabContent-2">
                        @foreach(activeLanguages() as $lang)
                        <div class="tab-pane fade {{$loop->first ? 'active':''}} show" id="{{$lang->locale}}"
                            role="tabpanel" aria-labelledby="one-tab">
                            <div class="flex-divs mb-3">
                                <div class="input-block">
                                    <label>@lang('site.name') ( {{$lang->name}} )</label>
                                    <input value="{{$category->translate($lang->locale)['name']}}" type="text"
                                        name="{{$lang->locale}}[name]">

                                    @error($lang->locale.'.name')
                                    <span class="text-danger">{{$message}}</span>
                                    @enderror
                                </div>
                            </div>
                            @include('dashboard.includes.seo_inputs',['lang'=>$lang,'model'=>$category])
                        </div>

                        @endforeach

                        <div class="btm-part">
                            <h4 class="title mb-3">الصورة</h4>
                            <div class="flex-divs">
                                <div class="input-block">
                                    <input type="file" id="image" class="" name="photo" />
                                </div>
                            </div>
                            <div class="mt-2 flex-divs">
                                @if($category->photo !='')
                                <img class="image_preview"
                                    src="{{asset('images/library_categories/'.$category->photo)}}" alt="">

                                @else

                                <img class="image_preview" src="{{asset('default.png')}}" alt="">
                                @endif
                            </div>
                        </div>


                    </div>

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> حفظ</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('javascript')

@endpush

resources/views/dashboard/libraries/categories/index.blade.php
@extends('dashboard.layouts.master')
@push('style')
    <style>

    </style>
@endpush
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <div class="header-title">
                        <h4 class="card-title">إضافه قسم</h4>
                    </div>
                    @if(auth('admin')->user()->hasPermission('create_library_categories'))
                        <a href="{{route('library-categories.create')}}" class="btn btn-secondary add-list"><i class="las la-plus"></i>إضافه</a>
                    @endif
                </div>
                <div class="card-body">

                    @if(auth('admin')->user()->hasPermission('delete_library_categories'))
                        <button type="submit" class="btn  btn-danger mb-3" id="deleteAllBtn"><i class="las la-trash"></i> حذف المحدد</button>
                    @endif
                    <div class="table-responsive">
                        <form id="deleteAllForm" action="{{route('library-categories.bulkDelete')}}" method="post">
                            @csrf

                            <table id="datatable" class="table data-table table-bordered table-striped">
                                <thead>
                                <tr class="ligth">
                                    <th>
                                        <div class="checkbox d-inline-block">
                                            <input type="checkbox" class="checkbox-input" id="check_all">
                                            <label for="checkbox1" class="mb-0"></label>
                                        </div>
                                    </th>

                                    <th>الاسم</th>
                                    <th>العمليات</th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection
@push('javascript')


    <script>
        $('#datatable').DataTable({

            ajax: {
                url: "{{route('library-categories.data')}}"
            },
            columns: [
                {data: 'check_all', name: 'check_all'},
                {data: 'name', name: 'name'},

                {data: 'actions', name: 'actions'},
            ]
        })

    </script>
@endpush